### ISSUE TITLE
Can cicero be used on other organisms?

### ISSUE THREAD

**Issue by rLannes** [stjude/CICERO#108]
Hi!

I wanted to use cicero n drosophila, but you state that you only support 
CICERO currently supports GRCh37-lite and GRCh38_no_alt.
Is there anything I can do to make it works on fly?

Romain

**Comment by adthrasher** [comment]
We only provide reference files for the two human genomes listed. If the required reference files were created and assembled for drosophila, it may be possible to run CICERO. However, CICERO is highly tuned for human data and has not been tested on non-human data.

**Comment by rLannes** [comment]
I see, 
thank you for your answer.
