### ISSUE TITLE
/opt/cicero/src/bin/Cicero.sh: line 318: /usr/bin/find: Argument list too long

### ISSUE THREAD

**Issue by dade7** [stjude/CICERO#109]
Hi, 

connected to a closed issue:
https://github.com/stjude/CICERO/issues/73#issue-966727566

for certain samples I still get the "Argument list too long" error using find.
/opt/cicero/src/bin/Cicero.sh: line 318: /usr/bin/find: Argument list too long
/opt/cicero/src/bin/Cicero.sh: line 319: /usr/bin/find: Argument list too long

seems like it is connected to the "*" in the command. I manually tried the following:
`find ~/CICERO/sample1/CICERO_DATADIR/sample1_Aligned.out_sort/*/ -type f -name 'unfiltered.fusion.txt' -exec cat {} \; | sort -V -k 9,9 -k 10,10n -k 11,11n > ./TEST1_unfiltered.fusion.txt`
-bash: /usr/bin/find: Argument list too long

`find ~/CICERO/sample1/CICERO_DATADIR/sample1_Aligned.out_sort/ -type f -name 'unfiltered.fusion.txt' -exec cat {} \; | sort -V -k 9,9 -k 10,10n -k 11,11n > ./TEST2_unfiltered.fusion.txt`
this works

PS I am running RNApeg:v2.7.1 + CICERO version 1.8.1, however, as the find command is still the same, I expect to get the same error with the newest version

**Comment by adthrasher** [comment]
Please try version 1.9.5 of CICERO. I've updated that section to resolve this issue.

**Comment by dade7** [comment]
Thanks for the update. Now it runs. Best Dagmar
