### ISSUE TITLE
Failed to build docker image

### ISSUE THREAD

**Issue by JAYRJPT** [stjude/CICERO#110]
I am trying to build the Docker image. I have used the following command.
`sudo docker build -t stjude/cicero:0.2.0 .`
However I am getting the error-
```
! Installing the dependencies failed: Module 'YAML' is not installed, Module 'XML::LibXML' is not installed, Module 'Test::Most' is not installed, Module 'XML::LibXML::Reader' is not installed
! Bailing out the installation for BioPerl-1.7.8.
! Installing the dependencies failed: Module 'Bio::Root::Version' is not installed
! Bailing out the installation for Bio-SamTools-1.35.
102 distributions installed
The command '/bin/sh -c SAMTOOLS="/tmp/samtools-0.1.17" cpanm --force -i Bio::DB::Sam@1.35 && chown -R root:root /usr/local/.cpanm' returned a non-zero code: 1


```

Kindly give your suggestion.
Best
Jay

**Comment by adthrasher** [comment]
Hi Jay, are you attempting to build from the main branch or tagged release? Most users shouldn't need to build the Docker image as we provide pre-built images for each release: https://github.com/stjude/CICERO/pkgs/container/cicero. If you can provide some additional information on your use case, I can try to help resolve the issue.

**Comment by JAYRJPT** [comment]
I am trying to install the Docker image to detect the fusion transcript using Cicero.
Earlier I have installed the docker image using the same command in a different system. 
Should I Install it from the link(` https://github.com/stjude/CICERO/pkgs/container/cicero`) you have provided?

**Comment by adthrasher** [comment]
Yes, generally it is preferable to pull the prebuilt Docker images. For most users, building the Docker image from the Dockerfile would not be necessary. So I would recommend pulling the latest version of the Docker image (v1.9.3 currently) and using it directly.

**Comment by JAYRJPT** [comment]
Thanks for your suggestion.
