### ISSUE TITLE
-g vs -r 

### ISSUE THREAD

**Issue by sh-5** [stjude/CICERO#121]
Could you please let me know what to give for -g parameters and -r parameter? I tried few variations of the file paths given to these parameters. However, none of them seem to work.  

I downloaded the reference files - Cicero_reference/Homo_sapiens/GRCh37-lite/FASTA/GRCh37-lite.fa.

**Comment by sh-5** [comment]
what about the gtf file in GRCh37-lite in order to annotate with STAR?

**Comment by adthrasher** [comment]
The `-g` parameter is a string.

```
genome is either GRCh37-lite or GRCh38_no_alt. CICERO only supports the two human reference genome versions.
```

The `-r` parameter is a path to a directory.

```
refdir is the reference file directory specific to CICERO. Download [Reference Files](https://github.com/stjude/CICERO#reference) below. e.g. -r /home/user/software/CICERO/reference_hg38/ or -r /home/user/software/CICERO/reference_hg19/
```

So in your case above, you'd want the path to the `Cicero_reference` directory.

Our references bundles contain a GTF file, but you should consult the [STAR](https://github.com/alexdobin/STAR) documentation for appropriate values.
