### ISSUE TITLE
Cannot rebuild docker image

### ISSUE THREAD

**Issue by rannick** [stjude/CICERO#123]
Hello! 

I am trying to build a docker image with the given Dockerfile, without the last 2 lines 
```
ENTRYPOINT ["/opt/cicero/src/bin/Cicero.sh"]
CMD ["-h"]
```
as it is for a nextflow pipeline (nf-core/rnafusion) and nextflow by default expects a bash shell prompt and not the executable, but I have been unable to reproduce the build due to perl packages failing to install. 
Mostly it fails with error: `Installing the dependencies failed: Your Perl is not in the range '5.014'`
I have tried to install with other Perl versions but I am not a Perl expert and run into other errors, such as:
`env: ‘/run/rosetta/rosetta’: No such file or directory`

Would it be possible to provide an updated docker file?

**Comment by adthrasher** [comment]
Can you do something like the following? Then you won't need to build the container, you can just override the `ENTRYPOINT` and `CMD` directives.

```
FROM ghcr.io/stjude/cicero:v1.9.6
ENTRYPOINT ["bash"]
```

**Comment by rannick** [comment]
Thank you, it works perfectly
