### ISSUE TITLE
Dynamic blacklist

### ISSUE THREAD

**Issue by adthrasher** [stjude/CICERO#13]
Is this correct? It looks like this is a dynamic blacklist to handle highly recurrent genes, however, upon the first gene that falls under the threshold, it ends. Shouldn't it just skip to the next gene?

https://github.com/stjude/CICERO/blob/db198e1590d2008ba05c162d74c7fbe2ec177c90/src/bin/annotate.pl#L499

**Comment by drjrm3** [comment]
The skip idea sounds reasonable to me. The only reason I could think this would make sense is if the input was sorted and the `last if` was meant to short circuit to optimize but even in that case the simple skip would achieve the same biological meaning and only add slightly to the compute while increasing stability.

**Comment by adthrasher** [comment]
Good point, looking back the input is sorted, so it is meant to short-circuit
