### ISSUE TITLE
hg38 reference

### ISSUE THREAD

**Issue by alhafidzhamdan** [stjude/CICERO#21]
Hi there,
I'm interested in trying up CICERO but i was wondering if you've prepared the hg38 reference files?
Much appreciated! A

**Comment by liqingti** [comment]
We will put hg38 reference files soon, maybe next week.

Thanks,
Liqing

**Comment by adthrasher** [comment]
@alhafidzhamdan - Code updates to support hg38 have been completed and are now merged. You can grab the latest version (v0.3.0) and try it out. The README also now includes a download link for the hg38 reference files.

**Comment by adthrasher** [comment]
The updates are complete, so I'm going to close this issue. Please let us know if you run into any issues running hg38 samples.
