### ISSUE TITLE
RNApeg input for " -r refflat " and "-rg refflat" is not cleared

### ISSUE THREAD

**Issue by JAYRJPT** [stjude/CICERO#22]
I am running RNApeg via Docker to generate a junctions file for use by CICERO. However I am unable to understand what should be the input for " -r refflat " and "-rg refflat" in the code mentioned.
I have downloaded refflat file from UCSC and have used the following command.
`sudo docker run -v /home/deepak/:/home/deepak/ -v /media/deepak/Deepak4T/:/media/deepak/Deepak4T/ mnedmonson/public:rnapeg RNApeg.sh -b /media/deepak/Deepak4T/NEW_SAMPLE/SAMPLE_3/star/sample.sorted.bam -f /home/deepak/Downloads/reference/Homo_sapiens/GRCh37-lite/FASTA/GRCh37-lite.fa -r /home/deepak/Downloads/HG19REFFLAT`

I am getting the following error

**RNApeg.sh [-h] -b bamfile -f fasta -r refflat [-rg refflat]
ERROR: Output directory '/results' does not exist; need mountpoint?**

Where should be the input for the output directory in the command?

Kindly help to resolve the issue.
Thanks and Regards

**Comment by adthrasher** [comment]
You can use any local directory, but it must be named "/results" in the container so something like `-v <local path>:/results` as an argument to the docker command. So you could create a folder like `/home/deepak/rnapeg` then do `-v /home/deepak/rnapeg:/results`.

**Comment by JAYRJPT** [comment]
I am getting the following error-

`sudo docker run -v /home/deepak/rnapeg:/results -v /home/deepak/:/home/deepak/ -v /media/deepak/Deepak4T/:/media/deepak/Deepak4T/ mnedmonson/public:rnapeg RNApeg.sh -b /media/deepak/Deepak4T/SJBALL020016_C27.bam -f /home/deepak/Downloads/reference/Homo_sapiens/GRCh37-lite/FASTA/GRCh37-lite.fa -r /home/deepak/Downloads/HG19REFFLAT`


set REFGENE to default /home/deepak/Downloads/HG19REFFLAT
[*] Running junction_extraction_wrapper.pl
Sun Jul  5 09:35:45 2020: running: bam_junction.pl -type all -bam /media/deepak/Deepak4T/SJBALL020016_C27.bam -annotate -now -force 1 -out /results/SJBALL020016_C27.bam.junctions.tab -no-config -refflat /home/deepak/Downloads/HG19REFFLAT -fasta /home/deepak/Downloads/reference/Homo_sapiens/GRCh37-lite/FASTA/GRCh37-lite.fa
/usr/bin/env java -Xmx5g org.stjude.compbio.rnapeg.SplicedReadReporter -bam /media/deepak/Deepak4T/SJBALL020016_C27.bam -of /results/SJBALL020016_C27.bam.junctions.tab -refflat /home/deepak/Downloads/HG19REFFLAT -fasta /home/deepak/Downloads/reference/Homo_sapiens/GRCh37-lite/FASTA/GRCh37-lite.fa -annotate
ERROR: unknown format, expected 16 fields, has 9
ERROR: java.lang.ArrayIndexOutOfBoundsException: -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.stjude.compbio.rnapeg.Transcript.setup(Transcript.java:83)
	at org.stjude.compbio.rnapeg.Transcript.<init>(Transcript.java:51)
	at org.stjude.compbio.rnapeg.IntronCache.setup(IntronCache.java:50)
	at org.stjude.compbio.rnapeg.IntronCache.<init>(IntronCache.java:21)
	at org.stjude.compbio.rnapeg.SplicedReadReporter.main(SplicedReadReporter.java:737)
where is /results/SJBALL020016_C27.bam.junctions.tab at /RNApeg/src/bin/junction_extraction_wrapper.pl line 338.

**Comment by adthrasher** [comment]
Issue resolved via e-mail. To summarize, a different refflat file was used, which allowed RNApeg to complete successfully. The `SJBALL020016_C27.bam.junctions.tab.shifted.tab` file was then used for CICERO.
