### ISSUE TITLE
STAR and Picard parameters

### ISSUE THREAD

**Issue by kvaldez** [stjude/CICERO#27]
Hello!  I would like to use STAR and Picard to prepare my samples for CICERO.  Which parameters do you recommend for these tools?  Is RNApeg necessary, or can it be omitted?

Thanks!
Kristin

**Comment by adthrasher** [comment]
Hi Kristin, 

I would suggest using parameters similar to what we use for data deposited in [St. Jude Cloud](https://stjude.cloud/). The St. Jude Cloud RNA-Seq workflow is documented [here](https://stjudecloud.github.io/rfcs/0001-rnaseq-workflow-v2.0.0.html#workflow). 

RNApeg is optional but it will improve CICERO's performance. @liqingti can provide additional details. 

Thanks,

Andrew

**Comment by kvaldez** [comment]
Thank you!!

Kristin

**Comment by liqingti** [comment]
Hi Kristin,

In github, we have mentioned "junctions is the junctions file output from
RNApeg. See Generate Junctions
<https://github.com/stjude/CICERO#junctions> below.
CICERO can detect fusion by analysis of splice junction reads. If this
option is omitted, fusions generated by small deletions may be missed as
these events may lack the soft-clipped reads."

More details are in the method of our paper; there is a specific section.

Thanks,

Liqing

**Comment by kvaldez** [comment]
Thanks Liqing we'll install that as well.

Kristin
