### ISSUE TITLE
build the Docker image using the Dockerfile problem

### ISSUE THREAD

**Issue by hanxuelian** [stjude/CICERO#33]
When I use docker for software installation, the error message is as follows:
/bin/sh: 1: perlbrew: not found
The command '/bin/sh -c perlbrew --notest install 5.10.1' returned a non-zero code: 127

The command line is:
sudo docker build -t stjude/cicero:0.3.0 .

It may be that a line of commands in the Dockerfile needs to be changed.

**Comment by adthrasher** [comment]
Can you add the `--no-cache` option and try again, e.g. `sudo docker build --no-cache -t stjude/cicero:0.3.0 .`? If that does not work, can you provide some details about your environment and any error messages displayed during the Docker build?

**Comment by hanxuelian** [comment]
I tried sudo docker build --no-cache -t stjude/cicero:0.3.0 . and error messages were:

Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 locales all 2.27-3ubuntu1.2 [3603 kB]
debconf: delaying package configuration, since apt-utils is not installed
....
....
Step 12/38 : RUN curl -kL http://install.perlbrew.pl | bash
 ---> Running in fd44e32b90fa
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170  100   170    0     0     35      0  0:00:04  0:00:04 --:--:--    36
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
Removing intermediate container fd44e32b90fa
 ---> 3ac033f39960
Step 13/38 : ENV PATH /usr/local/perlbrew/bin:$PATH
 ---> Running in cc23fdc9d7f3
Removing intermediate container cc23fdc9d7f3
 ---> 951a2adfeabf
Step 14/38 : ENV PERLBREW_PATH /usr/local/perlbrew/bin
 ---> Running in adc7e68183a5
Removing intermediate container adc7e68183a5
 ---> 9d5b5c8ea908
Step 15/38 : ENV PERL_VERSION 5.10.1
 ---> Running in 910c05863810
Removing intermediate container 910c05863810
 ---> 773ee7bf9506
Step 16/38 : RUN perlbrew --notest install 5.10.1
 ---> Running in 5779d92654cd
/bin/sh: 1: perlbrew: not found
The command '/bin/sh -c perlbrew --notest install 5.10.1' returned a non-zero code: 127

Sincerely,
Xuelian Han



xuelian2008ing@sina.com
 
From: Andrew Thrasher
Date: 2020-09-01 20:56
To: stjude/CICERO
CC: hanxuelian; Author
Subject: Re: [stjude/CICERO] build the Docker image using the Dockerfile problem (#33)
Can you add the --no-cache option and try again, e.g. sudo docker build --no-cache -t stjude/cicero:0.3.0 .? If that does not work, can you provide some details about your environment and any error messages displayed during the Docker build?

**Comment by adthrasher** [comment]
Looking at your output, running `curl -kL http://install.perlbrew.pl` produces an error `curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused`. Can you try running the command manually on whatever machine you are performing the Docker build? It looks like a networking issue.

**Comment by hanxuelian** [comment]
The errors that have been reported are perlbrew: not found.When I did not install perlbrew separately through Dockerfile, it was successful.

We installed CICERO through Dockerfile on another linux server and it also failed.I guess if the statements in the Dockerfile are not written correctly, which leads to the inability to install perlbrew correctly in a separate container.

Sincerely,
Xuelian Han



xuelian2008ing@sina.com
 
From: Andrew Thrasher
Date: 2020-09-02 20:48
To: stjude/CICERO
CC: hanxuelian; Author
Subject: Re: [stjude/CICERO] build the Docker image using the Dockerfile problem (#33)
Looking at your output, running curl -kL http://install.perlbrew.pl produces an error curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused. Can you try running the command manually on whatever machine you are performing the Docker build? It looks like a networking issue.

**Comment by adthrasher** [comment]
Perlbrew is not found because your Docker build is erroring when attempting to retrieve the perlbrew installer. 

Below is the output from a complete run of the Docker build. Note that the `curl` command reports a second connection, whereas yours only reports the first. The machine you are attempting to build on is not connecting to the GitHub properly to download the file. Try editing the Dockerfile to add the verbose argument to the `curl` command. That may provide additional information to help determine the source of the connection failure.

```bash
Step 12/38 : RUN curl -kL http://install.perlbrew.pl | bash
 ---> Running in 85a4f3fdb6c6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170  100   170    0     0    639      0 --:--:-- --:--:-- --:--:--   639
100  1554  100  1554    0     0   3356      0 --:--:-- --:--:-- --:--:--  3356

## Download the latest perlbrew

## Installing perlbrew
Using Perl </usr/bin/perl>
perlbrew is installed: ~/perlbrew/bin/perlbrew

perlbrew root (~/perlbrew) is initialized.

Append the following piece of code to the end of your ~/.bash_profile and start a
new shell, perlbrew should be up and fully functional from there:

    source ~/perlbrew/etc/bashrc

Simply run `perlbrew` for usage details.

Happy brewing!

## Installing patchperl

## Done.
```

**Comment by hanxuelian** [comment]
running curl -kL http://install.perlbrew.pl did not succeed,Can I install perlbrew in other ways in the Dockerfile, because I don’t know how to modify the Dockerfile. Can you help me modify a version and I will try docker installation again.

Sincerely,
Xuelian Han



hanxl@borenhospital.com
 
From: xuelian2008ing@sina.com
Date: 2020-09-03 09:05
To: stjude/CICERO; stjude/CICERO
CC: Author
Subject: Re: Re: [stjude/CICERO] build the Docker image using the Dockerfile problem (#33)
The errors that have been reported are perlbrew: not found.When I did not install perlbrew separately through Dockerfile, it was successful.

We installed CICERO through Dockerfile on another linux server and it also failed.I guess if the statements in the Dockerfile are not written correctly, which leads to the inability to install perlbrew correctly in a separate container.

Sincerely,
Xuelian Han



xuelian2008ing@sina.com
 
From: Andrew Thrasher
Date: 2020-09-02 20:48
To: stjude/CICERO
CC: hanxuelian; Author
Subject: Re: [stjude/CICERO] build the Docker image using the Dockerfile problem (#33)
Looking at your output, running curl -kL http://install.perlbrew.pl produces an error curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused. Can you try running the command manually on whatever machine you are performing the Docker build? It looks like a networking issue.

**Comment by adthrasher** [comment]
Most likely whatever server you are using to build has networking restrictions. You should discuss with your organization's IT. Another option would be to build the Docker image on a machine with fewer restrictions (maybe a laptop instead of a server). You can always use `docker save` and `docker load` to transfer the image to another machine once it is built.
