### ISSUE TITLE
Singularity RNApeg

### ISSUE THREAD

**Issue by mehc555** [stjude/CICERO#34]
Hi,

I get this error when trying to run RNApeg with singularity 3.5.3:

[*] Running junction_extraction_wrapper.pl
Tue Sep  8 16:52:27 2020: running: bam_junction.pl -type all -bam test.bam -annotate -now -force 1 -out test.bam.junctions.tab -no-config -refflat refFlat.txt -fasta GRCh37-lite.fa
Can't locate JavaRun.pm in @INC (you may need to install the JavaRun module)

Any ideas?

Thanks

**Comment by adthrasher** [comment]
Try adding the`--containall` argument to singularity. It appears that your local Java environment may be interfering with the Java environment in the container.

**Comment by mehc555** [comment]
When I add that option it cannot find the files anymore (with or without fullpath). Any other option to add ?

singularity run --containall --bind results:/results docker://mnedmonson/public:rnapeg RNApeg.sh -b test.bam -f test.fa -r test.refFlat
ERROR: Bamfile 'test.bam' DNE

**Comment by adthrasher** [comment]
You will need to use bind mounts (`--bind`) to mount the necessary locations into the container. The `--containall` parameter isolates the container from the local environment, similar to the normal state when using Docker.

**Comment by mehc555** [comment]
Works, thanks
