### ISSUE TITLE
ERROR: no local reference sequence found for BAM reference name chr1_KI270762v1_alt

### ISSUE THREAD

**Issue by JAYRJPT** [stjude/CICERO#54]
I am running Running RNApeg via Docker.
Here is my command
`sudo docker run -v /home/deepak/rnapeg:/results -v /home/deepak/:/home/deepak/ -v /media/deepak/Deepak4T/:/media/deepak/Deepak4T/ mnedmonson/public:rnapeg RNApeg.sh -b /media/deepak/Deepak4T/B1_dedup_reads.bam -f /home/deepak/Downloads/reference/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa -r /home/deepak/Downloads/reference/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt`
However I am getting the following error

**ERROR: no local reference sequence found for BAM reference name chr1_KI270762v1_alt
ERROR: no local reference sequence found for BAM reference name chr1_KI270766v1_alt
ERROR: no local reference sequence found for BAM reference name chr1_GL383518v1_alt**
.
.
.
**ERROR: no local reference sequence found for BAM reference name chr19_GL949752v1_alt
ERROR: no local reference sequence found for BAM reference name chr6_KI270758v1_alt
ERROR: no local reference sequence found for BAM reference name chr19_GL949753v2_alt
ERROR: no local reference sequence found for BAM reference name chr19_KI270938v1_alt
ERROR: java.io.IOException: BAM header not fully compatible with specified reference sequence
java.io.IOException: BAM header not fully compatible with specified reference sequence
	at org.stjude.compbio.rnapeg.SplicedReadReporter.report(SplicedReadReporter.java:241)
	at org.stjude.compbio.rnapeg.SplicedReadReporter.main(SplicedReadReporter.java:744)
where is /results/B1_dedup_reads.bam.junctions.tab at /RNApeg/src/bin/junction_extraction_wrapper.pl line 338**

I have done STAR 2 mode alignment using **"Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa"**  followed by 
Mark Duplicates using Picard.

Kindly help to resolve the issue.
Thanks and Regards,
Jay

**Comment by adthrasher** [comment]
The `GRCh38_no_alt` reference files do not include the ALT contigs. It appears that the input BAM was aligned to a version of the reference genome containing the ALT contigs.

**Comment by kskuchin** [comment]
If I'm doing my own STAR alignment before the RNApeg step using your GRCh37-lite reference, does it matter which annotation .gtf version I use?

**Comment by JAYRJPT** [comment]
> The `GRCh38_no_alt` reference files do not include the ALT contigs. It appears that the input BAM was aligned to a version of the reference genome containing the ALT contigs.

I have again done the STAR alignment using **Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa** and .gtf file downloaded from GENCODE.
Although, I am able to get the junctions file from RNApeg but I got some errors.

**tossing novel chr8:109563531:+,chr8:109564439:+: fails flanking QC, raw count: 3
tossing novel chr8:120440245:+,chr8:120443185:+: fails flanking QC, raw count: 4
.
.
tossing novel chrUn_GL000216v2:13641:+,chrUn_GL000216v2:40692:+: not bi-directional, fails read counts
tossing novel chrUn_GL000219v1:78098:+,chrUn_GL000219v1:78842:+: fails flanking QC, raw count: 3
tossing novel chrUn_GL000220v1:106159:+,chrUn_GL000220v1:107073:+: not bi-directional, fails read counts
.
.
can't find map for chr14_KI270726v1_random, ref=chr14_KI270726v1_random
can't find map for chr14_tossing novel chr8:109563531:+,chr8:109564439:+: fails flanking QC, raw count: 3
tossing novel chr8:120440245:+,chr8:120443185:+: fails flanking QC, raw count: 4
.
.
tossing novel chrUn_GL000216v2:13641:+,chrUn_GL000216v2:40692:+: not bi-directional, fails read counts
tossing novel chrUn_GL000219v1:78098:+,chrUn_GL000219v1:78842:+: fails flanking QC, raw count: 3
tossing novel chrUn_GL000220v1:106159:+,chrUn_GL000220v1:107073:+: not bi-directional, fails read counts
.
.
can't find map for chr14_KI270726v1_random, ref=chr14_KI270726v1_random
can't find map for chr14_KI270726v1_random, ref=chr14_KI270726v1_random
can't find map for chr1_KI270706v1_random, ref=chr1_KI270706v1_random
.
.
can't find map for chrY_KI270740v1_random, ref=chrY_KI270740v1_random
NOTE: auto_qc not enabled for /results/B1sorted.bam.junctions.tab.shifted.tab.annotated.tab
rows skipped (no gene match): 0
rows hitting > 1 gene: 15591
KI270726v1_random, ref=chr14_KI270726v1_random
can't find map for chr1_KI270706v1_random, ref=chr1_KI270706v1_random
.
.
can't find map for chrY_KI270740v1_random, ref=chrY_KI270740v1_random
NOTE: auto_qc not enabled for /results/B1sorted.bam.junctions.tab.shifted.tab.annotated.tab
rows skipped (no gene match): 0
rows hitting > 1 gene: 15591**

After running Cicero with Docker , I got some of the warnings
Here is the log file
```
Step 01 - 2021.03.15 17:36:05 - ExtractSClips
CICERO_DATADIR/B1sorted/B1sorted.chr14.10001.16099999.cover has no soft clipped reads
Step 02 - 2021.03.15 20:05:47 - Cicero
Step 03 - 2021.03.15 22:35:59 - Combine
Step 04 - 2021.03.15 22:35:59 - Annotate
Step 05 - 2021.03.16 06:41:25 - Filter
Killing blat server with pid 225
Killing   225 ?        00:22:02 gfServer

```
Should I again look into my bam file to fix these errors? 
or these are just the information.

**Comment by JAYRJPT** [comment]
> The `GRCh38_no_alt` reference files do not include the ALT contigs. It appears that the input BAM was aligned to a version of the reference genome containing the ALT contigs.


I have again done the STAR alignment using Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa and .gtf file downloaded from GENCODE.
Although, I am able to get the junctions file from RNApeg but I got some warnings

**tossing novel chr8:109563531:+,chr8:109564439:+: fails flanking QC, raw count: 3
tossing novel chr8:120440245:+,chr8:120443185:+: fails flanking QC, raw count: 4
.
.
tossing novel chrUn_GL000216v2:13641:+,chrUn_GL000216v2:40692:+: not bi-directional, fails read counts
tossing novel chrUn_GL000219v1:78098:+,chrUn_GL000219v1:78842:+: fails flanking QC, raw count: 3
tossing novel chrUn_GL000220v1:106159:+,chrUn_GL000220v1:107073:+: not bi-directional, fails read counts
.
.
can't find map for chr14_KI270726v1_random, ref=chr14_KI270726v1_random
can't find map for chr14_tossing novel chr8:109563531:+,chr8:109564439:+: fails flanking QC, raw count: 3
can't find map for chr1_KI270706v1_random, ref=chr1_KI270706v1_random
can't find map for chrY_KI270740v1_random, ref=chrY_KI270740v1_random

NOTE: auto_qc not enabled for /results/B1sorted.bam.junctions.tab.shifted.tab.annotated.tab
rows skipped (no gene match): 0
rows hitting > 1 gene: 15591**

Can we fix these errors ?

**Comment by JAYRJPT** [comment]
I have used proteinpaint to visualize final fusion txt. but it is showing many invalid isoforms.

`26 invalid isoforms: NM_000982-LOCB, NM_001289975-LOCA, NM_001329857-LOCA, NM_001329858-LOCA, NM_013450-LOCA, NM_001206840, NM_001206841, NM_182626, NM_001330240-LOCA, NM_001330244-LOCA, NM_001145029, NM_001346870-LOCB, NM_001042490-LOCB, NM_022892-LOCB, NM_001098728-LOCB, NM_001354437-LOCB, NM_001354438-LOCB, NM_001354439-LOCB, NM_001364567-LOCB, NM_001364568-LOCB, NM_001364569-LOCB, NM_001364570-LOCB, NM_001364571-LOCB, NM_001364572-LOCB, NM_001364573-LOCB, NM_001515-LOCB`

Also only 5 fusion is in "HQ" rating rest all fusion falling under "LQ" rating. 
How many fusion of HQ rating do we expect from one sample?

**Comment by adthrasher** [comment]
> If I'm doing my own STAR alignment before the RNApeg step using your GRCh37-lite reference, does it matter which annotation .gtf version I use?

@kskuchin - Please open a separate issue or discussion for your question.

**Comment by adthrasher** [comment]
> I have used proteinpaint to visualize final fusion txt. but it is showing many invalid isoforms.
> 
> `26 invalid isoforms: NM_000982-LOCB, NM_001289975-LOCA, NM_001329857-LOCA, NM_001329858-LOCA, NM_013450-LOCA, NM_001206840, NM_001206841, NM_182626, NM_001330240-LOCA, NM_001330244-LOCA, NM_001145029, NM_001346870-LOCB, NM_001042490-LOCB, NM_022892-LOCB, NM_001098728-LOCB, NM_001354437-LOCB, NM_001354438-LOCB, NM_001354439-LOCB, NM_001364567-LOCB, NM_001364568-LOCB, NM_001364569-LOCB, NM_001364570-LOCB, NM_001364571-LOCB, NM_001364572-LOCB, NM_001364573-LOCB, NM_001515-LOCB`
> 
> Also only 5 fusion is in "HQ" rating rest all fusion falling under "LQ" rating.
> How many fusion of HQ rating do we expect from one sample?

The number of fusions will vary with sample type and many other factors.
