### ISSUE TITLE
frameness? 

### ISSUE THREAD

**Issue by ahdee** [stjude/CICERO#57]
Hi is there a way to have Cicero output the frame predictions? Such as, in.frame, out.of.frame or undetermine? 

edit: I notice 2 colums, frame and sv_frame but can't make out how to utilized these to determine the frame. 

thanks!

**Comment by adthrasher** [comment]
@mnedmonson - Can you describe these two columns from the frame check? 

I believe there is a numeric code [0,3] with blank also a possibility. 
0 - event is not in frame
1 - event is in-frame
2 - geneB portion contains canonical coding start site
3 - possible 5' UTR fusion in geneB
