### ISSUE TITLE
Interpretation of output spanning reads and discordant reads

### ISSUE THREAD

**Issue by ashleyzhou972** [stjude/CICERO#59]
I was wondering if there's a more detailed description of the output columns,
The only resource I could find was here: https://university.stjude.cloud/docs/genomics-platform/workflow-guides/rapid-rnaseq/#interpreting-results, and the [FusionEditor help page](https://docs.google.com/document/d/1LgcMk_p1qyPgFPQChy4sLlU9GDL6oahffP7jJfD8ZwE/edit). Neither of those resources contain definitions for columns such as `matchA`, `repeatA`, `coverageA`, or `ratioA`.

Specifically, I have the following questions:
- If the `readsA` and `readsB` columns in `final_fusions.txt` are columns containing number of **chimeric reads** for a fusion, why are the two having different values for the same fusion? By definition a chimeric read should contain sequences from both A and B genes.

- Are there metrics equivalent to star-fusion's `JunctionReadCount` and `SpanningFragCount` columns? According to STAR-Fusion [wiki](https://github.com/STAR-Fusion/STAR-Fusion/wiki#output-from-star-fusion), the former  "indicates the number of RNA-Seq fragments containing a read that aligns as a split read at the site of the putative fusion junction", and the latter "indicates the number of RNA-Seq fragments that encompass the fusion junction such that one read of the pair aligns to a different gene than the other paired-end read of that fragment".

If you could illustrate how CICERO's output `readsA` and `readsB` columns (or maybe other columns) relate to these two concepts, to enable us to do a more thorough comparison of the two methods, that would be great!

Thank you!

**Comment by adthrasher** [comment]
The FusionEditor has a [link](https://docs.google.com/document/d/1jkVYRPIJpkWvA9vqtahRlNn63Hk5DehjHbF_BH9k7Rs/edit) to the file format. @liqingti - Can you answer the questions about the read counts?
