### ISSUE TITLE
Update CGC CWL to use CGC docker repo

### ISSUE THREAD

**Issue by adthrasher** [stjude/CICERO#75]
Also update the docker version in the CWL during the CGC deploy to point to a version, rather than latest.

**Comment by jordan-rash** [comment]
So I will start working on this.  Seems that we are going to (if we are going to automate this) need to build a deployment file after the rest of the pipeline it complete.  This is something I think the action I have it primed to do.  I will start working on it

**Comment by adthrasher** [comment]
For DNAnexus (https://github.com/stjude/CICERO/blob/master/.github/workflows/publish_dx.yml) I have a placeholder value in the tool definition (CICERO_SHORT_VERSION) which I use sed to replace during the build process before deploying. I'm open to other suggestions as well, but that is a fairly simple method.
