### ISSUE TITLE
Error when installing CICERO via docker on ArchLinux

### ISSUE THREAD

**Issue by GACGAMA** [stjude/CICERO#83]
Hello everyone

I'm trying to install cicero using docker.
I've succesfully ran RNApeg (for now) with installation using docker.

But when I try to install CICERO via docker I get the following error:

```
docker build -t stjude/cicero:1.4.0 https://github.com/stjude/CICERO/blob/master/Dockerfile

Error response from daemon: dockerfile parse error line 7: unknown instruction: <!DOCTYPE
```

I've also tried to download the docker file and run it locally, with the same error.

Output of` docker version`
```

Client:
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d28e
 Built:             Wed Aug  4 10:59:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d88bc
  Built:            Wed Aug  4 10:58:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.5
  GitCommit:        72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by adthrasher** [comment]
If you want to build the Docker image manually, you need to clone the entire repository. You cannot build it by using the URL of the Dockerfile in GitHub. As of v1.5.1, we provide a pre-built Docker image in GitHub packages, so you can use it directly. You can use the following command to run the latest version (v1.8.1) by updating the command with your paths: `docker run -v <path to reference directory>:/reference -v <path to data directory>:/data ghcr.io/stjude/cicero:v1.8.1 Cicero.sh [-n cores] -b <bam file path> -g <genome> -r /reference -o <output directory> [-j junctions file] [-p] [-s int] [-t int] [-c int]`
