### ISSUE TITLE
gfServer fails to start/is aborted.

### ISSUE THREAD

**Issue by jcdaneshmand** [stjude/CICERO#93]
Hello all,

I've been trying to run CICERO on a collection of bams aligned to Grch_38_no_alt.  I've already run picard to mark/remove duplicates and RNApeg as well to get the junction files.  Upon running CICERO, the help screen for gfServer appears and I get a message saying the gfServer was aborted.  The err and log files are very similar, attached is the log:

> 2022/02/16 02:35:43: error: gfServer v 37x1 - Make a server to quickly find where DNA occurs in genome
   To set up a server:
      gfServer start host port file(s)
      where the files are .2bit or .nib format files specified relative to the current directory
   To remove a server:
      gfServer stop host port
   To query a server with DNA sequence:
      gfServer query host port probe.fa
   To query a server with protein sequence:
      gfServer protQuery host port probe.fa
   To query a server with translated DNA sequence:
      gfServer transQuery host port probe.fa
   To query server with PCR primers:
      gfServer pcr host port fPrimer rPrimer maxDistance
   To process one probe fa file against a .2bit format genome (not starting server):
      gfServer direct probe.fa file(s).2bit
   To test PCR without starting server:
      gfServer pcrDirect fPrimer rPrimer file(s).2bit
   To figure out if server is alive, on static instances get usage statics as well:
      gfServer status host port
     For dynamic gfServer instances, specify -genome and optionally the -genomeDataDir
     to get information on an untranslated genome index. Include -trans to get about information
     about a translated genome index
   To get input file list:
      gfServer files host port
   To generate a precomputed index:
      gfServer index gfidx file(s)
     where the files are .2bit or .nib format files.  Separate indexes are
     be created for untranslated and translated queries.  These can be used
     with a persistent server as with 'start -indexFile or a dynamic server.
     They must follow the naming convention for for dynamic servers.
   To run a dynamic server (usually called by xinetd):
      gfServer dynserver rootdir
     Data files for genomes are found relative to the root directory.
     Queries are made using the prefix of the file path relative to the root
     directory.  The files $genome.2bit, $genome.untrans.gfidx, and
     $genome.trans.gfidx are required. Typically the structure will be in
     the form:
         $rootdir/$genomeDataDir/$genome.2bit
         $rootdir/$genomeDataDir/$genome.untrans.gfidx
         $rootdir/$genomeDataDir/$genome.trans.gfidx
     in this case, one would call gfClient with 
         -genome=$genome -genomeDataDir=$genomeDataDir
     Often $genomeDataDir will be the same name as $genome, however it
     can be a multi-level path. For instance:
          GCA/902/686/455/GCA_902686455.1_mSciVul1.1/
     The translated or untranslated index maybe omitted if there is no
     need to handle that type of request.
     The -perSeqMax functionality can be implemented by creating a file
         $rootdir/$genomeDataDir/$genome.perseqmax

> options:
>    -tileSize=N     Size of n-mers to index.  Default is 11 for nucleotides, 4 for
>                    proteins (or translated nucleotides).
>    -stepSize=N     Spacing between tiles. Default is tileSize.
>    -minMatch=N     Number of n-mer matches that trigger detailed alignment.
>                    Default is 2 for nucleotides, 3 for proteins.
>    -maxGap=N       Number of insertions or deletions allowed between n-mers.
>                    Default is 2 for nucleotides, 0 for proteins.
>    -trans          Translate database to protein in 6 frames.  Note: it is best
>                    to run this on RepeatMasked data in this case.
>    -log=logFile    Keep a log file that records server requests.
>    -seqLog         Include sequences in log file (not logged with -syslog).
>    -ipLog          Include user's IP in log file (not logged with -syslog).
>    -debugLog       Include debugging info in log file.
>    -syslog         Log to syslog.
>    -logFacility=facility  Log to the specified syslog facility - default local0.
>    -mask           Use masking from .2bit file.
>    -repMatch=N     Number of occurrences of a tile (n-mer) that triggers repeat masking the
>                    tile. Default is 2252.
>    -noSimpRepMask  Suppresses simple repeat masking.
>    -maxDnaHits=N   Maximum number of hits for a DNA query that are sent from the server.
>                    Default is 100.
>    -maxTransHits=N Maximum number of hits for a translated query that are sent from the server.
>                    Default is 200.
>    -maxNtSize=N    Maximum size of untranslated DNA query sequence.
>                    Default is 40000.
>    -maxAaSize=N    Maximum size of protein or translated DNA queries.
>                    Default is 8000.
>    -perSeqMax=file File contains one seq filename (possibly with ':seq' suffix) per line.
>                    -maxDnaHits will be applied to each filename[:seq] separately: each may
>                    have at most maxDnaHits/2 hits.  The filename MUST not include the directory.
>                    Useful for assemblies with many alternate/patch sequences.
>    -canStop        If set, a quit message will actually take down the server.
>    -indexFile      Index file create by `gfServer index'. Saving index can speed up
>                    gfServer startup by two orders of magnitude.  The parameters must
>                    exactly match the parameters when the file is written or bad things
>                    will happen.
>    -timeout=N      Timeout in seconds.
>                    Default is 90.
> 
> 2022/02/16 02:35:43: error: gfServer aborted

this is the command I am running:

```
docker run -v ${CICERO_REFERENCES}:/reference \
-v ${bam_dir}:/bamdir \
-v ${genome}:/fasta \
-v ${outdir_cicero}:/out \
-v ${outdir_rnapeg}:/rnapeg \
ghcr.io/stjude/cicero:latest Cicero.sh \
-n 4 \
-b /bamdir/${i}_marked_duplicates.bam \
-g GRCh38_no_alt.fa \
-r /reference \
-o /out \
-j /rnapeg/${i}_marked_duplicates.bam.junctions.tab.shifted.tab
```

I made sure BLAT and gfServer are installed in  usr/local/bin which is in the $PATH, and so should be accessible to Cicero.sh.  I've also made sure the CICERO scripts folder is in the $PATH and the perl5libs dependencies are in $PERL5LIB.  It just seems like the gfServer isn't launching and I'm not sure why.  I've also tried running Cicero in docker with the same results.  Could it have to do with the port? This is being done on an azure compute VM, with ubuntu.  Can anyone help me?

**Comment by adthrasher** [comment]
In your command invocation, the `-g` parameter should be `-g GRCh38_no_alt`. Adding `.fa` is likely breaking CICERO's ability to find the appropriate reference files. Can you retry and let me know if that resolves the issue?

**Comment by jcdaneshmand** [comment]
Thank you so much!! I suspected it was some small issue with the command I overlooked...  Cicero is running now on all my inputs, and there was no issue with starting up the gfServer.  Thanks :)
