### ISSUE TITLE
Final Fusion List Missing

### ISSUE THREAD

**Issue by alfonso-lam** [stjude/CICERO#95]
Hi,
I downloaded CICERO and I tested the docker image using the demo data provided in the repo.
For some reason, the final fusion file is missing.  Not sure what I missed. Here are the commands I executed:

RNApeg:
docker run -v /mnt/storage/data/cicero/reference/:/mnt/ref/ -v /mnt/storage/data/cicero/bam/demo/:/mnt/bam/ -v /mnt/storage/an
alysis/fusions/cicero/:/mnt/output/ rnapeg -b /mnt/bam/MV4_11_RNAseq_1.bam -f /mnt/ref/Homo_sapiens/GRCh37-lite/FASTA/GRCh37-lite.fa -r /mnt/ref/Homo_sapiens/GRCh37-lite/mRNA/RefSeq/refFlat.txt -rg /mnt/ref/Homo_sapiens/GRCh37-lite/mRNA/RefSeq/refFlat.txt -O /mnt/output/

cicero:
docker run -v /mnt/storage/data/cicero/reference/:/mnt/ref/ -v /mnt/storage/data/cicero/bam/demo/:/mnt/bam/ -v /mnt/storage/an
alysis/fusions/cicero/:/mnt/output/ --memory="8g" --memory-swap="20g" cicero:latest -b /mnt/bam/MV4_11_RNAseq_1.bam -r /mnt/ref/ -o /mnt/output/ -j /mnt/output/MV4_11_RNAseq_1.bam.junctions.tab.shifted.tab -g GRCh37-lite -n 32

I got the files:

01_ExtractSClips.err
01_ExtractSClips.log
01_ExtractSClips.out
02_Cicero.err
02_Cicero.log
02_Cicero.out
03_Combine.err
03_Combine.out
04_Annotate.err
04_Annotate.log
04_Annotate.out
05_Filter.err
05_Filter.out
MV4_11_RNAseq_1.bam.junctions.tab
MV4_11_RNAseq_1.bam.junctions.tab.shifted.bed
MV4_11_RNAseq_1.bam.junctions.tab.shifted.tab
MV4_11_RNAseq_1.bam.junctions.tab.shifted.tab.annotated.tab

CICERO_CONFIG
CICERO_DATADIR
CICERO_RUNDIR

And:
 ls -1d CICERO_DATADIR/MV4_11_RNAseq_1/*txt
CICERO_DATADIR/MV4_11_RNAseq_1/annotated.all.txt
CICERO_DATADIR/MV4_11_RNAseq_1/annotated.internal.txt
CICERO_DATADIR/MV4_11_RNAseq_1/excluded.new.fusions.txt
CICERO_DATADIR/MV4_11_RNAseq_1/excluded.new.internal.txt
CICERO_DATADIR/MV4_11_RNAseq_1/final_internal.txt
CICERO_DATADIR/MV4_11_RNAseq_1/MV4_11_RNAseq_1.gene_info.txt
CICERO_DATADIR/MV4_11_RNAseq_1/MV4_11_RNAseq_1.SC.txt
CICERO_DATADIR/MV4_11_RNAseq_1/unfiltered.fusion.txt
CICERO_DATADIR/MV4_11_RNAseq_1/unfiltered.internal.txt

When I check the files:
wc -l  CICERO_DATADIR/MV4_11_RNAseq_1/*txt
      1 CICERO_DATADIR/MV4_11_RNAseq_1/annotated.all.txt
      1 CICERO_DATADIR/MV4_11_RNAseq_1/annotated.internal.txt
      0 CICERO_DATADIR/MV4_11_RNAseq_1/excluded.new.fusions.txt
      0 CICERO_DATADIR/MV4_11_RNAseq_1/excluded.new.internal.txt
      0 CICERO_DATADIR/MV4_11_RNAseq_1/final_internal.txt
  24731 CICERO_DATADIR/MV4_11_RNAseq_1/MV4_11_RNAseq_1.gene_info.txt
 136746 CICERO_DATADIR/MV4_11_RNAseq_1/MV4_11_RNAseq_1.SC.txt
      0 CICERO_DATADIR/MV4_11_RNAseq_1/unfiltered.fusion.txt
      0 CICERO_DATADIR/MV4_11_RNAseq_1/unfiltered.internal.txt

What did I miss?
Thanks a lot in advance.

**Comment by RECranston** [comment]
Hi,

Sorry to piggyback on this issue but I am facing the same problem.

I also do not get a final fusion file and CICERO seems to fail, with the following message:
/opt/cicero/src/bin/Cicero.sh: line 390:   228 Terminated              gfServer start $BLAT_HOST $BLAT_PORT "$TWOBIT" -log=${GFSERVER_LOG}.log -stepSize=5 >> ${GFSERVER_LOG}.out 2>> ${GFSERVER_LOG}.err  (wd: /mnt/output)

I ran RNApeg without issue using the following command:
docker run -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/demo_data:/mnt/ref -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/demo_data:/mnt/bam -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/demo_data:/mnt/output ghcr.io/stjude/rnapeg:latest -b /mnt/bam/MV4_11_RNAseq_1.bam -f /mnt/ref/GRCh37.fa -r /mnt/ref/refFlat.txt -rg /mnt/ref/refFlat.txt -O /mnt/output

And this is the command I used to run CICERO:
docker run -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/demo_data/reference:/mnt/ref -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/demo_data:/mnt/bam -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/demo_data:/mnt/output ghcr.io/stjude/cicero:latest -b /mnt/bam/MV4_11_RNAseq_1.bam -r /mnt/ref -o /mnt/output -j /mnt/output/MV4_11_RNAseq_1.bam.junctions.tab.shifted.tab -n 32 -g GRCh37-lite

I'm also facing the same issue and error message using GRCh38_no_alt with my own data. Any suggestions would be greatly appreciated.

Cheers,
Ruth

**Comment by RECranston** [comment]
Hi,

Thanks so much for your response. I've got this working now. 

I did have an RNAPeg output but I was running RNAPeg using a refflat.txt downloaded from [here](http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/refFlat.txt.gz) and .fa file downloaded from ensembl. When I used the St Judes references for RNAPeg ([GRCh37-lite](https://doi.org/10.5281/zenodo.3817656) or [GRCh38_no_alt](https://doi.org/10.5281/zenodo.3894739) as listed on the CICERO github homepage I managed to run CICERO successfully.

Final commands:
RNAPeg command
`docker run -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/13_12_22_MV411_test/GRCh37_lite_reference:/mnt/ref -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/13_12_22_MV411_test/bam_files:/mnt/bam -v /home/data/RNA_Seq/AML_Illumina/CICERO_ru
n/13_12_22_MV411_test/output:/mnt/output ghcr.io/stjude/rnapeg:v2.7.5 -f /mnt/ref/Homo_sapiens/GRCh37-lite/FASTA/GRCh37-lite.fa -b /mnt/bam/MV4_11_RNAseq_1.bam -r /mnt/ref/Homo_sapiens/GRCh37-lite/mRNA/RefSeq/refFlat.txt -rg /mnt/ref/Hom
o_sapiens/GRCh37-lite/mRNA/RefSeq/refFlat.txt -O /mnt/output`

CICERO command
`docker run -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/13_12_22_MV411_test/GRCh37_lite_reference:/mnt/ref -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/12_12_22_MV411_test/bam_files:/mnt/bam -v /home/data/RNA_Seq/AML_Illumina/CICERO_ru
n/13_12_22_MV411_test/RNAPeg_output:/mnt/junc -v /home/data/RNA_Seq/AML_Illumina/CICERO_run/13_12_22_MV411_test/output:/mnt/output ghcr.io/stjude/cicero:latest -b /mnt/bam/MV4_11_RNAseq_1.bam -r /mnt/ref -j /mnt/junc/MV4_11_RNAseq_1.bam.
junctions.tab.shifted.tab -n 32 -g GRCh37-lite -o /mnt/output`

Thanks again for your help, it is much appreciated!
