### ISSUE TITLE
ERROR: unrecognized parameter RNApeg.sh

### ISSUE THREAD

**Issue by dade7** [stjude/CICERO#96]
Hi,
when running RNApeg like mentioned in the readme, I get the error message "ERROR: unrecognized parameter RNApeg.sh".
I have to skip the "RNApeg.sh" (see command below), then it runs. 
Best, Dagmar

```
docker run  --user=$(id -u):$(id -g) \
	   -v /etc/localtime:/etc/localtime:ro \
	   -v ${RNApeg_outdir}:/results \
	   -v ${star_outdir}:/bamdir:ro \
	   -v ${refFlatfile}:/refFlat:ro \
	   -v ${fastadir}:/fastadir:ro \
	   -v ${cicero_ref}:/refdir \
	   ghcr.io/stjude/rnapeg:v2.7.1 -b /bamdir/${sampleID}_Aligned.out_sort.bam \
	   -f /fastadir/${fastafile} -r /refFlat
```

**Comment by adthrasher** [comment]
@dade7 Thanks for the report! I've updated and pushed out the documentation change. Let us know if you encounter anything else.
